backend/models/SmsConfigurations.php
<?php

namespace backend\models;

use Yii;
use backend\models\SmsTemplates;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "sms_configurations".
 *
 * @property integer $id
 * @property string $label
 * @property integer $templeate_id
 */
class SmsConfigurations extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sms_configurations';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['label'], 'required'],
            [['templeate_id'], 'integer'],
            [['label'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'label' => 'Label',
            'templeate_id' => 'Templeate ID',
        ];
    }
    public function getTemplateModel(){
        return $this->hasOne(SmsTemplates::className(),['id'=>'templeate_id']);
    }

    public function loadAll() {
        return SmsConfigurations::find()->all();
    }

    public function getTempleatesList() {
        $data = SmsTemplates::find()
            ->where(['status' => '1'])
            ->all();
        return ArrayHelper::map($data, 'id', 'label');

    }
    public function loadSmsTemplateData($id) {
        return $data = SmsTemplates::find()
            ->where(['id'=> $id])->asArray()->one() ;
    }
}

backend/controllers/SmsConfigurationsController.php
<?php

namespace backend\controllers;

use backend\components\AdminController;
use backend\models\SmsConfigurations;
use yii;

class SmsConfigurationsController extends AdminController
{
    public function actionIndex()
    {	
    	$smsConfig = new SmsConfigurations;
    	$smsConfigData = $smsConfig->loadAll();
    	if($smsConfig->load(yii::$app->request->post())) {
    		$updateData = $smsConfig->templeate_id;
    		foreach ($updateData as  $key => $value) {
    			$configItem = SmsConfigurations::findOne($key);
    			$configItem->templeate_id = $value;
    			$configItem->save();
    		}
    		Yii::$app->session->setFlash('success','SMS configuration updated');
    		return $this->redirect(['sms-configurations/index']);
    		
    	}
        return $this->render('index', [
        	'smsConfig' => $smsConfig,
        	'smsConfigData' => $smsConfigData
        ]);
    }

    public function actionViewSmsTemplate($id) {
    	$smsConfig = new SmsConfigurations();
    	$loadResponse = $smsConfig->loadSmsTemplateData($id);
    	if($loadResponse) {
    		$response = [
    			'status' => true,
    			'data' => $loadResponse
    		];
    	} else {
    		$responseresponse = [
    			'status' => false,
    			'data' => [],
    		];
    	}
    	return json_encode($response, JSON_PRETTY_PRINT);
    }

}

backend/views/sms-configurations/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

$this->title = 'SMS Configurations';
$this->params['breadcrumbs'][] = 'Configurations'; 
$this->params['breadcrumbs'][] = $this->title; 

?>

<div class="sms-configurations bg-fff">
	<div class="row">
		<div class="col-xs-12">
			<div class="page-info-box">
				<p>  <i class="fa fa-info" aria-hidden="true"></i> Want to manage the existing SMS template or want to create the custom template ? <?=Html::a('Click Here', ['/sms-templates/index'],['class'=> ''])?>  </p>
			</div>
		</div>
	</div>
	<?php $form = ActiveForm::begin(); ?>
	<?php foreach ($smsConfigData as $key =>  $item) { ?>
	<div class="row">
		<div class="col-xs-6">

			<?= $form->field($item, 'templeate_id['.$item->id.']')->widget(Select2::classname(), [
			    'data' => $smsConfig->getTempleatesList(),
			    'options' => ['placeholder' => 'select', 'class'=> 'controller-input', 	'data-viewid'=>$item->id, 'value'=> $item->templeate_id],
			    'pluginOptions' => [
			        'allowClear' => true
			    ],
			])->label($item->label) ?>
		</div>
		<div class="col-xs-6">
			<div class="messag-view">
				<p id="view<?=$item->id?>"> <?php if($item->templateModel) { 
					echo $item->templateModel->content;
				}
				?> </p> 
			</div>
		</div>
	</div>
	<?php } ?>
	<div class="row">
		<div class="col-xs-12">
			<div class="form-group pull-right">
		        <?= Html::submitButton($smsConfigData[0]->isNewRecord ? 'Create' : 'Update', ['class' => $smsConfigData[0]->isNewRecord ? 'btn btn-success' : 'btn btn-primary theme-btn pull-right']) ?>
		    </div>
		    <div class="clearfix"> </div>
		</div>
	</div>
	<?php ActiveForm::end(); ?>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		$(".controller-input").change(function () {
			var id = $(this).val();
			var viewId = $(this).attr('data-viewid');
			$.ajax({
                method: 'GET',
                dataType: 'json',
                url: '/sms-configurations/view-sms-template?id=' + id,
                crossDomain: false,
                success: function(responseData, textStatus, jqXHR) {
                    $("#view" + viewId).text(''+ responseData.data.content+'');
                            
            	},
	            error: function (responseData, textStatus, errorThrown) {
		        },
	        }); 
			
			// alert("changed");
		});
	});
</script>

<style type="text/css">
	.messag-view {
	    padding: 15px;
	    background: #dde1e2;
	    margin: 10px;
	    border-radius: 11px;
	}
</style>