backend/controllers/AccountsController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\User;
use backend\models\search\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\components\AdminController;
use backend\models\search\SchemeJoinsSearch;
use backend\models\SchemeJoins;
use backend\models\InvestmentJoins;
use backend\models\search\InvestmentJoinsSearch;
use backend\models\B2cAddress;
use common\models\SignupForm;
use yii\web\Session;
use kartik\mpdf\Pdf;
/**
 * AccountsController implements the CRUD actions for User model.
 */
class AccountsController extends AdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */

    public function actionGetOfferDetails() {
        if(Yii::$app->request->post()) {
            $schemeOffer = new \backend\models\SchemeOffers();
            $offerId = $_POST['offerId'];
            $activeOfferArray = $schemeOffer->findOne($offerId);
            $activeArray = [];
            foreach ($activeOfferArray as $key => $value) {
                   $activeArray [$key] = $value;
            }
            print_r(json_encode($activeArray,true));

        }
    }

    public function actionUpdateUserDetails() {
        //$model = new User();
        if(yii::$app->request->post()) {
            $post = yii::$app->request->post();
            $userData = User::find()
                ->where(['id'=>$post['User']['id']])
                ->one();
                // if(!empty($post['B2cAddress']['roots'])) {
                //     $userData->b2cAddressModel->roots = implode(', ',array_filter($post['B2cAddress']['roots']));  
                // } else {
                //     $userData->b2cAddressModel->roots = '';
                // }
            $userData->b2cAddressModel->roots = $post['B2cAddress']['roots'];
            if($userData->b2cAddressModel->save()) {
                Yii::$app->session->setFlash('success', 'Roots has been Updated');
                return $this->redirect(Yii::$app->request->referrer);
            }
        }else {
            return $this->redirect(Yii::$app->request->referrer);
        }
    }


    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['level'=>'4']);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $userModel = new User();

        $searchModel = new SchemeJoinsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['u_id'=>$id]);
        $dataProvider->query->orderBy(['id' => SORT_DESC]);
        $dataProvider->pagination = ['pageSize' =>4];
        $investmentSearchModel = new InvestmentJoinsSearch();
        $investmentDataProvider = $investmentSearchModel->search(Yii::$app->request->queryParams);
        $investmentDataProvider->query->andWhere(['u_id'=>$id]);
        $investmentDataProvider->query->orderBy(['id' => SORT_DESC]);
        $investmentDataProvider->pagination = ['pageSize' =>4];

        $userSummaryInfo = $userModel->loadAccountInfo($id);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'userSummaryInfo' => $userSummaryInfo,
            'investmentSearchModel' => $investmentSearchModel,
            'investmentDataProvider' => $investmentDataProvider,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */





    public function actionTest() {
    $session = new Session;
    $session->open();
       print_r($session['lastPasswdUser']);
    }

    public function actionAccountValidate() {

        $model = new \common\models\UserValidation();
        
        if($model->load(Yii::$app->request->post())) {
            if($model->type==0) {
                $validateAccountStatus = User::find()
                    ->where(['status'=>10,'level'=>4])
                    ->andWhere(['mobile'=>$model->mobile])
                    ->one();
                if(!empty($validateAccountStatus)&& count($validateAccountStatus)>0) {
                    Yii::$app->session->setFlash('info', 'found a valid account with customer informations');
                    return $this->redirect(['/accounts/view','id'=>$validateAccountStatus->id]);
                }
                else {
                    Yii::$app->session->setFlash('info', 'please create a new account!');
                    return $this->redirect(['/accounts/create','mobile'=>$model->mobile]);  
                }
            }
            else if($model->type==1) {
                $validateAccountStatus = User::find()
                    ->where(['status'=>10,'level'=>4])
                    ->andWhere(['email'=>$model->email])
                    ->one();
                if(!empty($validateAccountStatus) && count($validateAccountStatus)>0) {
                    Yii::$app->session->setFlash('info', 'found a valid account with customer informations');
                    return $this->redirect(['/accounts/view','id'=>$validateAccountStatus->id]);
                }
                else {
                    Yii::$app->session->setFlash('info', 'please create a new account!');
                    return $this->redirect(['/accounts/create','email'=>$model->email]);  
                }
            }   
        }
        else {

            return $this->renderAjax('account-validate',[
                'model'=>$model,
            ]);

        }
        
    }

    public function actionCreate()
    {   
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                Yii::$app->session->setFlash('success', 'Account has been created');
                return $this->redirect(['/accounts/view','id'=>$user->id]);
            }
        }
        else {

            $mobile = yii::$app->request->get('mobile');
            $email = yii::$app->request->get('email');
            return $this->render('signup', [
                'model' => $model,
                'mobile' => $mobile,
                'email' => $email,
            ]);

        }

       
    }

    public function actionCreateInvestment() {
        $model = new SignupForm();
        $model->is_investment = true;
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->investment_signup()) {
                Yii::$app->session->setFlash('success', 'Account has been created');
                return $this->redirect(['/accounts/view','id'=>$user->id]);
            }
        }   
        else {

            $mobile = yii::$app->request->get('mobile');
            $model->email = $mobile.yii::$app->params['virtualEmailDomain'];
            return $this->render('signup_investment', [
                'model' => $model,
                'mobile' => $mobile
            ]);

        }
    }

    public function actionJoinNewScheme($user_id) {
        
        $model = new SignupForm();
        if($model->load(Yii::$app->request->post())) {
            $newSchemeJoin = $model->newSchemeJoin();
            if($newSchemeJoin=='true') {
                Yii::$app->session->setFlash('success','New Scheme has been registered!');
                return $this->redirect(['/accounts/view', 'id'=>$user_id]);

            }
        }
        else {
            return $this->render('join-new-scheme', [
                'model' => $model,
                'userId'=>$user_id,
            ]);
        }


    }

    public function actionReciptTest() {
        return $this->render('_test');
    }

    public function actionRecipt($join_id) {

        $model = SchemeJoins::findOne($join_id);
        $userModal = User::find()->where(['id'=>$model->u_id])->one();
        $addressModal = B2cAddress::find()->where(['u_id'=>$model->u_id])->one();
        
        
        
        $content = $this->renderPartial('_test',[
            'model'=>$model,
            'userModal' => $userModal,
            'addressModal' => $addressModal,
            'cacheP' => $this->getPrintPasswordVisibility($userModal->id),
        ]);
    
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE, 
            // A4 paper format
            'format' => Pdf::FORMAT_LETTER, 
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER, 
            // your html content input
            'content' => $content,
            'marginTop' => 0,
            'marginRight' => 0,
            'marginLeft' => 0,
            'marginBottom' => 0,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
             // set mPDF properties on the fly

backend/views/accounts/_scheme-list.php
<?php 
use yii\helpers\Html;

$completedScale = $model->paid_duration/$model->duration*100;

if($completedScale<=29) {
	$progressBarHtml='<div class="progress-bar progress-bar-red" style="width:'.$completedScale.'%"></div>';
}
else if($completedScale<=49 && $completedScale>30) {
	$progressBarHtml='<div class="progress-bar progress-bar-yellow" style="width:'.$completedScale.'%"></div>';
}
else if ($completedScale<=69 && $completedScale>50) {
	$progressBarHtml='<div class="progress-bar progress-bar-aqua" style="width:'.$completedScale.'%"></div>';
}
else if ($completedScale>70) {
	$progressBarHtml='<div class="progress-bar progress-bar-green" style="width:'.$completedScale.'%"></div>';
}
?>

<div class="progress-group">
    <span class="progress-text"> <?=$model->plan_label?></span>
 	<span class="progress-number"><b><?=$model->paid_duration?>/<?= $model->duration.'</b> Payment Paid'?></span>
 	<div class="progress sm">
      <?=$progressBarHtml?>
   	</div>
   	<div class="bn btn-group pull-right">
   		<?= Html::a('Print', ['/accounts/recipt','join_id'=>$model->id], ['target'=>'_blank','class' => 'btn theme-btn bg-maroon']) ?>
   		<?= Html::a('view', ['/scheme-joins/view','join_id'=>$model->id], ['target'=>'_blank','class' => 'btn theme-btn btn-primary']) ?>
  		
   	</div>
   	<div class="clearfix"> </div>
</div>

backend/views/accounts/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;    
/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="user-index bg-fff">
    <div class="row searchbox">
            <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <p> <?= Html::a('Create User', ['/accounts/account-validate'], ['class' => 'btn btn-success bootstrap-modal-new theme-btn pull-right','data-title'=>'User already on the system ?','data-width'=>'30%']) ?> </p>
            <?php Pjax::begin(); ?>
            <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'class' => 'table -custom',
            'rowOptions' => function ($model, $key, $index, $grid) {
                return ['data-href' => '/accounts/view?id=' . $model->id];
            },
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],


                'username',
                'f_name',
                'l_name',
                'mobile',
                [   
                    'header'=>'Join Date',
                    'value'=> function($model) {
                        return date('d-m-Y h:i A',$model->created_at);
                    },
                ],
                [   
                    'header'=>'Action',
                    'format'=> 'raw',
                    'value'=> function($model) {
                        return Html::a('<i class="fa fa-eye"> </i> View',['/sss'],['classs'=>'ssss']);
                    },
                ],
            ],
            ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('table tr[data-href]').click(function () {
            if ($(this).data('href') !== undefined) {
                window.location.href = $(this).data('href');
            }
        });
    });
</script>

backend/views/accounts/join-new-scheme.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;
use kartik\widgets\DatePicker;
use backend\components\widgets\MaterialCheckbox;

$packages = new backend\models\Packages();
$period = new backend\models\Periodes();
$schemeOffers = new backend\models\schemeOffers();

$this->title = 'Join New Scheme';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
<div class="nav-tabs-custom form-new bg-fff">
    <ul class="nav nav-tabs">
        <li class="active" id="tab-h-1"><a href="#tab_1" data-toggle="tab" aria-expanded="false">Offer Information</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab_1">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                 
                 <?= $form->field($model, 'scheme')->widget(Select2::classname(), [
                    'data' => $packages->generatePackageLists(),
                    'language' => 'en',
                    'options' => ['placeholder' => 'select'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                  ]); ?>

                  <?= $form->field($model, 'period')->widget(Select2::classname(), [
                    'data' => $period->generatePeriodeLists(),
                    'language' => 'en',
                    'options' => ['placeholder' => 'select'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                  ]); ?>
                  <?= $form->field($model, 'offer')->widget(Select2::classname(), [
                    'data' => $schemeOffers->generateSchemeOffersLists(),
                    'language' => 'en',
                    'options' => ['placeholder' => 'select'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                  ]); ?>

                  <?= $form->field($model,'user_id')->hiddenInput(['value'=>$userId])->label(false)?>

                  <?= $form->field($model, 'valid_from')->widget(DatePicker::classname(), [
                  'options' => ['placeholder' => 'Customer plan valid from'],
                      'pluginOptions' => [
                          'autoclose'=>true,
                          'todayHighlight' => true,
                          'format' => 'yyyy-mm-dd',
                          'autoclose' => true,
                          'startDate' => date("yyyy-MM-dd H:i:s"),

                      ]
                  ]); ?>


                  
            </div>
            <div class="col-xs-12 col-sm-6">
                
              <div class="box box-info" id="loader-block">
                <div class="box-header with-border">
                  <h3 class="box-title">Offer Summary</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="table-responsive">
                    <table class="table no-margin">
                     
                      <tbody>
                        <tr>
                          <td style="width:60%"><b>Free Month Bonus</b></td>
                          <td style="width:40%" id="monthBonusDetails"><span class="label label-success">Shipped</span></td>
                        </tr>
                        <tr>
                          <td style="width:60%"><b>Free Cash Bonus</b></td>
                          <td style="width:40%" id="cashBonusDetails"><span class="label label-success">Shipped</span></td>
                        </tr>
                        <tr>
                          <td style="width:60%"><b>Free Gold Bonus</b></td>
                          <td style="width:40%" id="goldBonusDetails"><span class="label label-success">Shipped</span></td>
                        </tr>
                        <tr>
                          <td style="width:60%"><b>Offer Availing on</b></td>
                          <td style="width:40%" id="offerAvailingOn"><span class="label label-success">Shipped</span></td>
                        </tr>
                        
                      </tbody>
                    </table>
                  </div><!-- /.table-responsive -->
                </div><!-- /.box-body -->
              </div>
               <?= $form->field($model, 'startup_payment')->dropDownlist(['0'=>'Yes','1'=>'No'],['prompt'=>'startup Payment']) ?>
            </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12">
            <div class="form-group pull-right">
              <?= Html::submitButton('Signup', ['class' => 'btn btn-primary theme-btn', 'name' => 'signup-button']) ?>
            </div>
          </div>
        </div>

      </div><!-- /.tab-pane -->
      
      
    </div><!-- /.tab-content -->
</div>
<?php ActiveForm::end(); ?>

<script type="text/javascript">
$( document ).ready(function() {
  
   $("#loader-block").hide();

  function replaceDetails(data) {
      if(data.bonus_cash!=null) {
        $("#cashBonusDetails").html('<span class="label label-success">'+data.bonus_cash+' Ruppess  </span>');
      }
      else if (data.bonus_cash==null) {
        $("#cashBonusDetails").html('<span class="label label-danger">Not Available</span>');
      }
      if (data.bonus_gold!=null) {
          $("#goldBonusDetails").html('<span class="label label-success">'+data.bonus_gold+' Grams </span>');
      }
      else if (data.bonus_gold==null) {
          $("#goldBonusDetails").html('<span class="label label-danger">Not Available</span>');
      }
      if (data.bonus_month==null) {
          $("#monthBonusDetails").html('<span class="label label-danger">Not Available </span>');
      }
      else if (data.bonus_month=='1') {
          $("#monthBonusDetails").html('<span class="label label-success"> 1 Month </span>');
      }
      else if (data.bonus_month!=null) {
          $("#monthBonusDetails").html('<span class="label label-success">'+data.bonus_month+' Months</span>');
      }
      if(data.offer_availing_on=='anytime') {
        $("#offerAvailingOn").html('<span class="label label-info">Anytime</span>');
      }
      else if (data.offer_availing_on=='end_of') {
        $("#offerAvailingOn").html('<span class="label label-info">End of period </span>');
      }
  }

   $("#signupform-offer").change(function() {
        $("#loader-block").show();
        run_waitMe();
        var offerId = $(this).val();
        
        if(offerId==null) {
          $(".waitMe").hide();
          $("#loader-block").hide();
        }

        else {

          $.ajax({
                method: 'POST',
                url: '/accounts/get-offer-details',
                crossDomain: false,
                data:{'offerId':offerId},
                success: function(responseData, textStatus, jqXHR) {
                    var obj = JSON.parse(responseData);
                    replaceDetails(obj);
                    $(".waitMe").hide();
                            
            },
            error: function (responseData, textStatus, errorThrown) {
               $(".waitMe").hide();
               $("#loader-block").hide();
                
            },
        }); 

        }

         
    });




   function run_waitMe(effect){
    $('#loader-block').waitMe({

    //none, rotateplane, stretch, orbit, roundBounce, win8, 
    //win8_linear, ios, facebook, rotation, timer, pulse, 
    //progressBar, bouncePulse or img
    effect: 'roundBounce',

    //place text under the effect (string).
    text: 'Offer Details...',

    //background for container (string).
    bg: 'rgba(255,255,255,0.7)',

    //color for background animation and text (string).
    color: '#00aff0',

    //change width for elem animation (string).
    sizeW: '',

    //change height for elem animation (string).
    sizeH: '',

    // url to image
    source: '',

    // callback
    onClose: function() {}

    });
  }
  
});
</script>

backend/views/accounts/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;
use kartik\select2\Select2;
use yii\widgets\ActiveForm;



/* @var $this yii\web\View */
/* @var $model backend\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-xs-12 col-sm-8">
        <div class="box box-widget widget-user">
                
            <div class="widget-user-header bg-navy-active">
              <h3 class="widget-user-username"><?= $model->f_name.' '.$model->l_name ?></h3>
              <h5 class="widget-user-desc"><?= $model->mobile ?></h5>
            </div>
            <div class="widget-user-image">
              <img class="img-circle" src="/themes/adminlte/dist/img/avatar5.png" alt="User Avatar">
            </div>
            <div class="box-footer">
              <div class="row">
                <div class="col-sm-4 border-right">
                  <div class="description-block">
                    <h5 class="description-header"> <?=$dataProvider->getCount()?> </h5>
                    <span class="description-text"> Scheme Joins </span>
                  </div><!-- /.description-block -->
                </div><!-- /.col -->
                <div class="col-sm-4 border-right">
                  <div class="description-block">
                    <h5 class="description-header"> 
                        <?=money_format('%i',$userSummaryInfo['schemeInvestment'])?> </h5>
                    <span class="description-text">Ruppes Invested in Schemes</span>
                  </div><!-- /.description-block -->
                </div><!-- /.col -->


                <div class="col-sm-4">
                  <div class="description-block">
                    <h5 class="description-header"> <?= number_format($userSummaryInfo['totalInvestment'],2)?> </h5>
                    <span class="description-text">Ruppes Invested in General </span>
                  </div><!-- /.description-block -->
                </div><!-- /.col -->

              </div><!-- /.row -->
              <hr/>
                <div class="col-xs-12">
                    <div class="navbar navbar-default navbar-component navbar-xs">
                        <ul class="nav navbar-nav visible-xs-block">
                            <li class="full-width" style="padding-left: 15px;">
                                <a data-target="#navbar-filter-profile" data-toggle="collapse" class="collapsed" aria-expanded="false">
                                    <i class="fa fa-bars"></i> Menu
                                </a>
                            </li>
                        </ul>
                        <div id="navbar-filter-profile" class="navbar-collapse collapse custom-tab">
                            <ul class="nav navbar-nav ">
                                <li class="active"><a href="#tab_investments" data-toggle="tab" aria-expanded="false"><i class="fa fa-users" aria-hidden="true"></i> Investments </a></li>
                                <li class=""><a href="#tab_schemes" data-toggle="tab" aria-expanded="false"><i class="fa fa-search" aria-hidden="true"></i> Scheme Joins</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                    
                <div class="tab-content">
                    <div class="tab-pane active" id="tab_investments">
                        <div class="row">
                            <div class="col-xs-12">
                                 <?= ListView::widget([
                                    'dataProvider' => $investmentDataProvider,
                                    'layout' => "{summary}\n{items}\n<div class='pull-right'>{pager}</div>",
                                    'itemOptions' => ['class' => 'item'],
                                    'itemView' => '_investment-list',
                                    'pager' => [
                                        'prevPageLabel' => '<span class="glyphicon glyphicon-chevron-left"></span>',
                                        'nextPageLabel' => '<span class="glyphicon glyphicon-chevron-right"></span>',
                                    ],
                                    //'itemView' => function ($model, $key, $index, $widget) {
                                    //    return Html::a(Html::encode($model->id), ['view', 'id' => $model->id]);
                                   // },
                                ]) ?>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane " id="tab_schemes">
                       <div class="row">
                            <div class="col-xs-12">
                                <div style="padding: 15px">
                                     <?= ListView::widget([
                                            'dataProvider' => $dataProvider,
                                            'layout' => "{summary}\n{items}\n<div class='pull-right'>{pager}</div>",
                                            'itemOptions' => ['class' => 'item'],
                                            'itemView' => '_scheme-list',
                                            'pager' => [
                                                'prevPageLabel' => '<span class="glyphicon glyphicon-chevron-left"></span>',
                                                'nextPageLabel' => '<span class="glyphicon glyphicon-chevron-right"></span>',
                                            ],
                                            //'itemView' => function ($model, $key, $index, $widget) {
                                            //    return Html::a(Html::encode($model->id), ['view', 'id' => $model->id]);
                                           // },
                                        ]) ?>
                                </div>
                            </div>
                       </div>
                    </div>
                </div>


            </div>
        </div>

    </div>

    <div class="col-xs-12 col-sm-4">
        <div class="row">
            <div class="col-xs-12">
                <div class="btn-group pull-left">
                    <?=Html::a('<i class="fa fa-plus"></i> New Scheme',['/accounts/join-new-scheme','user_id'=>$model->id],['class'=>'btn btn-app theme-btn btn-app-bg-1'])?>
                    
                </div>
            </div>
        </div>
        <div class="row bg-fff">
            <?php $form = ActiveForm::begin([
                'action' => ['/accounts/update-user-details'],
                'id' => 'userConfigurationEdit'
            ]);


             $model->b2cAddressModel->roots = explode(', ',$model->b2cAddressModel->roots);
            ?>
            <?= $form->field($model,'id')->hiddenInput()->label(false)?>
            <?= $form->field($model->b2cAddressModel, 'roots')->widget(Select2::classname(), [
                'data' => $model->loadRootList(),
                'language' => 'en',
                'options' => ['placeholder' => 'Roots'],
                'pluginOptions' => [
                    'multiple' => false,
                    'allowClear' => true,
                ],
            ]); ?>
             <div class="form-group">
                <?= Html::submitButton('Update', ['class' => 'btn btn-primary theme-btn pull-right']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>

               
    </div>

</div>





<?php /*
<div class="row">

 <div class="col-xs-12 col-sm-6">
        <div class="item panel panel-default"><!-- widgetBody -->
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Account Details</h3>
                <div class="pull-right">
                    <div class="btn-group pull-right">
                       
                        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary theme-btn']) ?>
                        <?= Html::a('Suspend', ['update', 'id' => $model->id], ['class' => 'btn btn-danger theme-btn']) ?>
                        <!-- <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger theme-btn',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]) ?> -->
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                
                <div class="clients-view">
                      <?= DetailView::widget([
					        'model' => $model,
					        'attributes' => [
					            'id',
					            'username',
					            'f_name',
                                'l_name',
                                'mobile',
                                'email',
                                [
                                'attribute' => 'status',
                                'value' => function($model) { if($model->status==10) return'Active'; else return 'Inactive'; },
                                ],
					           
					        ],
					    ]) ?>  

                </div>
                
            </div>
        </div>
    </div>

</div>





<div class="user-view">
   
    

</div>
*/

?>


<style type="text/css">
    .investment-box {
    background: #7f96963d;
    padding: 10px;
    margin: 5px 15px;
}

.investment-box span {
    font-style: italic;
    color: #a94442;
}
.investment-box .body {
    text-align: right;
    margin-top: -43px;
    color: #a94442;
}
</style>